stages:
  - test

test: 
  stage: test
  image: golang:latest
  script: 
    - go env -w GOPRIVATE="git.foxminded.ua/foxstudent106264/"
    - git config --global url."https://foxstudent106264:glpat-8gAAzoSsg5R9Stocdz1-@gitlab.com".insteadOf "https://gitlab.com"
    - git config --global url."https://foxstudent106264:glpat-8gAAzoSsg5R9Stocdz1-@git.foxminded.ua".insteadOf "https://git.foxminded.ua"
    - go get git.foxminded.ua/foxstudent106264/tgapi@latest
    - go test -v ./...
    - go vet ./...
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - staticcheck ./...
    - go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
    - gocritic check main
    - gocritic check mocks
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - gosec -exclude=G107 ./...

test:golangci-lint:
  stage: test
  image: golangci/golangci-lint:v1.55.2
  script:
    - go env -w GOPRIVATE="git.foxminded.ua/foxstudent106264/"
    - git config --global url."https://foxstudent106264:glpat-8gAAzoSsg5R9Stocdz1-@gitlab.com".insteadOf "https://gitlab.com"
    - git config --global url."https://foxstudent106264:glpat-8gAAzoSsg5R9Stocdz1-@git.foxminded.ua".insteadOf "https://git.foxminded.ua"
    - go get git.foxminded.ua/foxstudent106264/tgapi@latest
    - golangci-lint run -v
    